### ISSUE TITLE
How to change question mark sign within square bracket i.e [?] in prompt?

### ISSUE THREAD

**Issue by sumit-kushwah** [magmax/python-inquirer#107]
I want replace [?] to something else.
Please help!!

![Screenshot 2020-10-29 at 10 28 48 PM](https://user-images.githubusercontent.com/39999765/97607072-84975b00-1a36-11eb-9e36-60cd3c06a4b4.png)

**Comment by Cube707** [comment]
this is currently not posible and I don't see a case where this has a usefull benifit
