### ISSUE TITLE
Selection color

### ISSUE THREAD

**Issue by walidsa3d** [magmax/python-inquirer#11]
It would be nice to be able to choose the color of the selecttion

**Comment by Zearin** [comment]
:+1:

**Comment by magmax** [comment]
Agree, but I cannot imagine the best way to support that. Any idea about how do you want to use that feature? Maybe setting it in the prompt object?

**Comment by walidsa3d** [comment]
@magmax  yes why not

**Comment by JohnLonginotto** [comment]
Any colour other than dark blue on black would be great.

**Comment by matiboy** [comment]
One could subclass the List renderer (and the others I guess) and the ConsoleRender to match that new List as below; the Render also needs to be instantiated in `prompt()`. But yeah maybe a dictionary `terminal_options={'select_symbol':'>', 'select_color': 'blue', .....}` would be nicer

```python
from inquirer.render.console import ConsoleRender
from inquirer.render.console._list import List

class OtherColorList(List):
    def get_options(self):
        choices = self.question.choices

        for choice in choices:
            selected = choice == choices[self.current]

            if selected:
                color = self.terminal.yellow
                symbol = '*'
            else:
                color = self.terminal.normal
                symbol = ' '
            yield choice, symbol, color

class OtherListConsoleRender(ConsoleRender):
    def render_factory(self, question_type):
        if question_type != 'list':
            return super(ConsoleRender, self).render_factory(question_type)
        return OtherColorList

questions = [
    inquirer.List('size',
                  message="What size do you need?",
                  choices=['Jumbo', 'Large', 'Standard', 'Medium', 'Small', 'Micro'],
              ),
]

answers = inquirer.prompt(questions, render=OtherListConsoleRender())
```

@magmax I can come up with a PR for this if you'd like?

**Comment by AuHau** [comment]
I believe this can be done using `theme` parameter of the `prompt()` function. See https://github.com/magmax/python-inquirer/blob/master/inquirer/themes.py

Hence I am closing this issue, feel free to reopen if this does not meet your criteria.
