### ISSUE TITLE
Heavy CPU usage while waiting for input in PowerShell

### ISSUE THREAD

**Issue by H0R5E** [magmax/python-inquirer#113]
Hi,

I noticed that when python-inquirer is waiting for input it is using a lot of CPU (probably a whole CPU thread) while waiting for input. I took these screenshots below:

![inquirer_wait](https://user-images.githubusercontent.com/5088535/118966410-9d7b4580-b961-11eb-982b-de42688ff928.png)

![inquirer_cpu](https://user-images.githubusercontent.com/5088535/118966413-9f450900-b961-11eb-9c62-71c5817de25e.png)

The version I am running is:

`inquirer                  2.7.0                      py_0    conda-forge`

It's in a conda environment being run in PowerShell on Windows 10 Pro.

Is this expected behaviour? Is there anyway to make it less hungry?

Many thanks,

Mat

**Comment by Cube707** [comment]
this comes from the underlying `readchar` libary which has a `while: True` loop in the windows implimentation. This is whats hogging all the CPU. (see https://github.com/magmax/python-readchar/issues/42)

The new `v4.0.0` fixes this but is only in pre-release right now. You can however test if it solves this issue if you want.

**Comment by H0R5E** [comment]
Sure, I'll give it a try.

**Comment by Cube707** [comment]
than use this to update your readchar version:

```bash
pip install -U --pre readchar
```

**Comment by H0R5E** [comment]
![low_cpu_usage](https://user-images.githubusercontent.com/5088535/181494975-0acc7a35-41f5-48d1-b26e-5de18b2b0e8b.PNG)

Solved! Looking forward to the full release.

**Comment by Cube707** [comment]
closed with the latest `readchar` release
