### ISSUE TITLE
Backspace not works on windows

### ISSUE THREAD

**Issue by mlabuda2** [magmax/python-inquirer#116]
Hi, I am testing inquirer on windows and unfortunately backspace not removing chars but adds \x08.
```>>> import inquirer
>>> username_text = inquirer.Text("username",message="Please enter your username")
>>> inquirer.prompt([username_text])
[?] Please enter your username: user
{'username': 'username \x08\x08\x08\x08    \x08\x08\x08\x08sss \x08\x08\x08\x08\x08 sss\x08\x08\x08 ss \x08\x08\x08  '}
>>>```

**Comment by mlabuda2** [comment]
Solution: https://github.com/magmax/python-readchar/issues/57

**Comment by xberry1231** [comment]
Not sure if I missed the solution in the other thread but this is what I was able to get work:

`for key in answers:
    while '\x08' in answers[key]:
        answers[key] = re.sub('[^\x08]\x08', '', answers[key])
`

**Comment by jens-coding** [comment]
same problem with linux via Mobaxterm (ssh-wrapper for Windows).
Also Mingw64 Bash Emulator on Windows: same problem.

Since this is fatal I would suggest to quickly produce a temporary fix, until the main failure reasons are clear.

**Comment by Moreless91** [comment]
> Not sure if I missed the solution in the other thread but this is what I was able to get work:
> 
> `for key in answers: while '\x08' in answers[key]: answers[key] = re.sub('[^\x08]\x08', '', answers[key]) `

This work around works until the user backspaces too many times and starts to erase your message string:

Then you end up in an infinite loop

**Comment by Cube707** [comment]
should be fixed in the latest version
