### ISSUE TITLE
Unable to delete the text input 

### ISSUE THREAD

**Issue by ajay15283** [magmax/python-inquirer#119]
While using inquirer.Text or inquirer.shortcuts.text in any case the value typed is wrong unable to delete and retype the correct input 

For eg:

[?] Provide the VM Size [example:Standard_B2s]: asdasdasdasd - Junk value entered , I need to delete and retype correct information, I know the "validation" can be an option but my question is when user realized he typed a wrong value and want to correct it 

If there is already an option available to overcome this problem please let me know 

OS : Linux
inquirer version 2.7.0
python: 3.6.13

**Comment by huhuang03** [comment]
same issue

**Comment by jonnieey** [comment]
Same issue

**Comment by skokado** [comment]
I faced the same issue.
So I did the following debugging into `inquirer.render.console._text.Text.process_input`

```diff
class Text(BaseConsoleRender):
    ...
    def process_input(self, pressed):
+       print("##", print(pressed))
        if pressed == key.CTRL_C:
```

- my_cli.py

```python
import inquirer

questions = [
    inquirer.Text("name", message="What's your name?"),
]

answers = inquirer.prompt(questions)
print(answers)
```

And, the result is as follows:

```shell
$ python3 my_cli.py
[?] What's your name?: a    # <= Pressed "a"
## None
[?] What's your name?: ab   # <= Pressed "b"
## None
[?] What's your name?: abc  # <= Pressed "c"
## None
[?] What's your name?: abc  # <= Pressed Backspace
## None
[?] What's your name?: abc  # <= Pressed Backspace
## None
[?] What's your name?: abc  # <= Pressed Enter
## None

{'name': 'abc\x7f\x7f'}
```

I think, `pressed` argument in `process_input()` is not passing values properly.
This library is too complex for me to give a PR for a quick fix, but I hope it helps :)

**Comment by skokado** [comment]
Sorry, there was an error in the above debugging code.

```diff
class Text(BaseConsoleRender):
    ...
    def process_input(self, pressed):
-       print("##", print(pressed))
+       print()
+       print('##', pressed, type(pressed))
        if pressed == key.CTRL_C:

```

It is natural that `print(... . print(pressed))` should result in `None`.
In any case, it looks like the Backspace key is not captured well.

```shell
[?] What's your name?:      # <= Pressed a
## a <class 'str'>
[?] What's your name?: a    # <= Pressed b
## b <class 'str'>
[?] What's your name?: ab   # <= Pressed c
## c <class 'str'>
[?] What's your name?: abc  # <= Pressed Backspace
##  <class 'str'>
[?] What's your name?: abc  # <= Pressed Backspace
##  <class 'str'>
[?] What's your name?: abc  # <= Pressed Enter
 <class 'str'>

{'name': 'abc\x7f\x7f'}
```

**Comment by alejandro-angulo** [comment]
I've also ran into this issue. I think the bug was introduced in 2.9.0 .

**Comment by zahedul** [comment]
face the same issue. so I downgrade the version

**Comment by tim-hitchins-ekkosense** [comment]
> I've also ran into this issue. I think the bug was introduced in 2.9.0 (I'm unable to reproduce this issue using 2.8.0).

2.9.1

**Comment by tim-hitchins-ekkosense** [comment]
This issue doesn't occur when installing directly from the github repo. Try
```
pip install git+https://github.com/magmax/python-inquirer@v2.9.1
```
and it will work. So I'm not sure what has been deployed to Pypi...

**Comment by eeriksp** [comment]
Installing directly from Github still produces the same issue. Tested on Ubuntu 21 with Python 3.10.

**Comment by shymmq** [comment]
I got the issue on v2.9.1, but not on v2.9.0 (both versions from PyPI).

**Comment by cleeistaken** [comment]
OSX 12.1
Python 3.9.5 
Inquirer 2.8.0: backspace works as expected
Inquirer 2.9.0: backspace does not work
Inquirer 2.9.1: backspace does not work

**Comment by OskarZyg** [comment]
not working on pop os 22.04 / python 3.10 with inquirer 2.9.2 either!

this is literally the most basic thing the library is supposed to be able to do, yet still cant handle text??

**Comment by Subetov** [comment]
inquirer==2.9.2
The same issue =(
Backspace doesn't work.
I can't remove or edit "default" value.

**Comment by OskarZyg** [comment]
Thanks, @ian-grover, that solution also works on Linux. Updated patch:
```py
import sys, readchar
```
```py
# fix inquirer
if any(x in sys.platform for x in ['darwin', 'linux']):
    # change readchar key backspace
    readchar.key.BACKSPACE = '\x7F'
```

I'll make a PR fixing this if I can.

**Comment by Cube707** [comment]
This is actually a problem with V3.0.5 of the underlying `readchar` libary. It accepted and shipped a bad PR with the latest Version. See: https://github.com/magmax/python-readchar/pull/76

**Comment by Cube707** [comment]
fixed with the new version of `readchar`, which is required by `inquirer` as per #206

**Comment by tekumara** [comment]
thanks @Cube707 upgrading to readchar 3.1.0 fixed this for me, eg:
```
pip install --upgrade readchar
```

**Comment by staticdev** [comment]
@Cube707 should this issue be closed then?

**Comment by Cube707** [comment]
From my side, yes. Your decision if you want to wait on feedback for the participants. But as they could just reopen, I would close it.
