### ISSUE TITLE
Is support windows?

### ISSUE THREAD

**Issue by awong1900** [magmax/python-inquirer#12]
On windows, 
import inquirer

error:
An error was found, but returning just with the version: No module named _curses

**Comment by sculove** [comment]
+1

**Comment by Bioinformix** [comment]
+1
When I installed _curses, it also doesn't worked:
An error was found, but returning just with the version: No module named fcntl

Light googling on "fcntl windows" tells that it kind of very low-lewel hard shit.

**Comment by Bioinformix** [comment]
Special for using this package I installed python 3.5, but it doesn't helps. :(

Windows 8 Pro x64, 
python 2.7
python 3.5

**Comment by danmichaelo** [comment]
Windows support won't happen unless it's added to blessings I guess: https://github.com/erikrose/blessings/issues/21

Would be nice if this was mentioned in the README.

**Comment by CITGuru** [comment]
I know this is old, but adding this might help others. [PyInquirer](https://github.com/CITGuru/PyInquirer/) works the same as python-inquirer. It does the same thing as Inquirer.js and works on all platforms. Its built on prompt_toolkit and has more components compared to blessings. Blessings is *nix native and no information if it will be supported on Windows yet. Its the best alternative you'd find.

**Comment by magmax** [comment]
I didn't knew pyinquirer :)

Anyways, python-inquirer is not a inquirer-js port, but it is based on it.

**Comment by CITGuru** [comment]
@magmax Yea. You should probably try PyInquirer for more support on differents platforms

**Comment by AuHau** [comment]
Information about platform suppor was added to README. I am closing this issue. For more information see #63
