### ISSUE TITLE
Confirm not work in version 2.1.6

### ISSUE THREAD

**Issue by chinakids** [magmax/python-inquirer#13]
use pip install inquirer only get version 2.1.6,not new 2.1.7

and inquirer.Confirm not work in version 2.1.6

```
Traceback (most recent call last):
  File "confirm.py", line 8, in <module>
    inquirer.Confirm('stop',"Should I stop",True),
TypeError: __init__() takes at most 3 arguments (4 given)
```

**Comment by chinakids** [comment]
i find this params must have name..

just like
```
inquirer.Confirm('ask', message=message, default=default)
```

**Comment by magmax** [comment]
Correct, you should use the named arguments.

You can see the examples folder in order to see how to use anything. That examples are the tests too, so they must be working.

Sorry for being late answering.
