### ISSUE TITLE
Ability to override questions defaults

### ISSUE THREAD

**Issue by lelit** [magmax/python-inquirer#14]
Maybe I'm missing something, but I was not able to pass an set of _pre answers_ to the `prompt()` function, to override the default values of the questions.

My use case is double: 
1. I'd like to implement a way to load predefined defaults from a file, before prompting the user
2. An application I wrote ([tinject](https://bitbucket.org/lele/metapensiero.tool.tinject)) has a _cascade_ of prompts, where any question may be repeated: at the second `prompt()` I'd like to be presented the answer given in the first, if any

At first I tried to use the `answers` argument to the `prompt()` function, but it didn't have any effect, and checking the source seems to confirm that.

In lelit@8480308fb09990f5dfe7f2214edf12923e6dd900 I modified the `default` property of the `Question` class to return the answered value, if present. Does that sound reasonable, or is there a better way to accomplish my goal?

**Comment by magmax** [comment]
Sounds reasonable and I like it.

**Comment by lelit** [comment]
Great, I'll do a PR, thank you!
