### ISSUE TITLE
CLI problem

### ISSUE THREAD

**Issue by 9Samzer** [magmax/python-inquirer#155]
Heyy !
When i am running on VSC, all works but when i try on .exe (Pyarmor + Pyinstaller), keys for switching selection in List prompt don't work. 
Im on Windows 10, thx

**Comment by rioqwerty1** [comment]
Same problem, wondering if this is fixed

**Comment by Cube707** [comment]
This is a windows problem on the underlaying `readchar` library. Same as with #156.


I provided a fix, but its still waiting to be merged (for a while...). See magmax/python-readchar#76

**Comment by Cube707** [comment]
`readchar` just released a new version that should fix this. Please confirm
