### ISSUE TITLE
`Checkbox` does not work when using Windows

### ISSUE THREAD

**Issue by saroad2** [magmax/python-inquirer#156]
Description
=======
When trying to use a `Checkbox` question, one cannot move the cursor up and down to select the boxes to check.

Example
======
Consider the following program:
```python
import inquirer

questions = [
    inquirer.Checkbox(
        "food",
        "What do you like to eat?",
        choices=["banana", "apple", "ice-creem"]
    )
]
answers = inquirer.prompt(questions)
print(answers)
```

Reproduction steps are:
1. Copy the code above
2. Run it on Windows computer in Power Shell
3. Check the banana option (*that works*)
4. Press the down arrow to move to the second option (*that doesn't work*)

Additional Information
===============
Windows 10
Python version: 3.9.5
Inquirer version: 2.9.1

**Comment by doubleailes** [comment]
Seems the same https://github.com/magmax/python-inquirer/issues/117
My work arround is to use numpad arrows

**Comment by RazvanCretu** [comment]
@doubleailes what if I have a loptop with no numpads?

**Comment by Cube707** [comment]
this will be fixed when https://github.com/magmax/python-readchar/pull/71 gets merged.

**Comment by Cube707** [comment]
I decided to take the time to provide a proper workaround as @magmax is currently not reacting.

Whoever needs an updatet version of python-readchar this urgently can install my fix from my fork by using `git+https://github.com/Cube707/python-readchar.git@v3.0.6` either in a `requirements.txt` file or directly from the comandline as:

```bash
pip install git+https://github.com/Cube707/python-readchar.git@v3.0.6
```

it is marked as version `3.0.6-dev0`, so it will override a existing `3.0.5` installation but will be overriden by a official version `3.0.6` release (when it's released...). See https://github.com/magmax/python-readchar/pull/76 for more information

I am also working on a version 4 of readchar (what @zixuan945 linked to above). As this will intreduce breaking chnages is is not fully developed jet, I would not recomend using that version.

**Comment by Cube707** [comment]
`readchar` just released a new version that should fix this. Please confirm
