### ISSUE TITLE
add to awesome-python list

### ISSUE THREAD

**Issue by lk-geimfari** [magmax/python-inquirer#16]
I found your library is very useful, and I want to thank you. Also I would also like to report that sent the pull request to add the library to the awesome-python list, and I hope you don't mind. It's can draw attention to your library, and more contributors who will help you with this lib.

**Comment by magmax** [comment]
cool!
Here it is the link to the awesome-python repository for anyone who may read this in the future: https://github.com/vinta/awesome-python

Anyway... I saw your pull-request, but the link is not shown in the main page.

**Comment by lk-geimfari** [comment]
@magmax I reopened the PR. Now we can only wait.
