### ISSUE TITLE
Avoid using O/X for checkboxes for the default theme

### ISSUE THREAD

**Issue by denilsonsa** [magmax/python-inquirer#166]
Hello, this is a suggestion to make the [default theme](https://github.com/magmax/python-inquirer/blob/master/src/inquirer/themes.py) for checkboxes less ambiguous and more clear.

![Screenshot showing the current default theme](https://user-images.githubusercontent.com/121676/167483230-2ab1e954-3c51-417c-b609-a157cd76b89c.png)

Currently, we have `Checkbox.selected_icon = "X"` and `Checkbox.unselected_icon = "o"`. However, this is not intuitive and can be quite confusing sometimes. If you consider the Japanese language ([1][], [2][]), the cross means NO and the circle means YES. Thus, if I have a checkbox displayed with either `X` or `o`, I could conclude `X` are the negation (or unmarked), while `o` are the selected.

What if you're not Japanese, or you don't know their language? Well, most people are familiar with video-games, and in many games the same symbols are used (across many consoles). Even the [PlayStation controller](https://en.wikipedia.org/wiki/PlayStation_controller) included the cross and the circle as buttons, originally with the meaning of NO and YES.

[1]: https://japanese.stackexchange.com/q/38508
[2]: https://english.stackexchange.com/q/397384

The [Inquirer.js project](https://github.com/SBoudrias/Inquirer.js/blob/inquirer%408.2.4/packages/checkbox/index.js#L96) avoids that issue by using unicode characters: [circle and circleFilled](https://github.com/sindresorhus/figures/blob/v4.0.1/index.js#L222-L223).

---

Thus, I would suggest replacing the `Checkbox.unselected_icon` with a plain underscore/underline symbol `_`. It's a symbol available anywhere on any encoding; and it looks empty, looks like a placeholder.

![Screenshot showing the first theme suggestion (although by mistake I also changed the "X" to lowercase "x"](https://user-images.githubusercontent.com/121676/167483120-c0b93202-8579-45a5-84f2-8750ecef21f5.png)

Alternatively, we could use `'[ ]'` and `'[x]'` as a three-character symbol. It looks good and very clear, but I'm afraid the additional 2 columns required for this look could impact some existing projects/users.

![Screenshot showing the second theme suggestion](https://user-images.githubusercontent.com/121676/167482979-7c76e7c4-3a0d-49ef-a93a-823612616d28.png)

**Comment by Cube707** [comment]
Hello, I see where you are comming from with this.

In generell this is exacly what thems are for. As usergroups affected by this require full unicode characters anyway, using `GreenPassion` or a custom them will be an obvious, uproblematic fix.

However, I like the idea of using `[ ]`/`[x]` as it matches Github/markdown and is indeed more clear. I also don't think three charactes should cause a problem. What do you think @staticdev?

**Comment by denilsonsa** [comment]
Huh, I think now someone needs to update the screenshots from the documentation:

* https://github.com/magmax/python-inquirer#checkbox
* https://magmax.org/python-inquirer/examples.html#checkbox-py
* Any other?
