### ISSUE TITLE
Missing Editor.opening_prompt_color on GreenPassion

### ISSUE THREAD

**Issue by AdrienPensart** [magmax/python-inquirer#169]
Hello, 
when using GreenPassion theme, inquirer.Editor does not work : 

> :x: AttributeError: type object 'editor' has no attribute 'opening_prompt_color'

easy fix in themes.py for class GreenPassion

```python
self.Editor.opening_prompt_color = term.bright_black
```

or you may derive GreenPassion from Default theme?

**Comment by Cube707** [comment]
good find. We should really inherit from `Default`
