### ISSUE TITLE
Why catch and swallow KeyboardInterrupt exceptions?

### ISSUE THREAD

**Issue by mmrwoods** [magmax/python-inquirer#18]
Hi,

First, thanks for your work on inquirer, I've used it to replace some custom interactive mode prompts on a cli app and it's a huge improvement on what we had before :-)

On thing that I found odd though, is the way inquirer catches KeyboardInterrupt exceptions, and doesn't re-raise them. This surprised me because I'd expect these exceptions to bubble up to the main/calling application, where they can be handled consistently regardless of where they occur.

Is there a specific reason for catching these exceptions within inquirer itself, or would you be open to accepting a pull request that either removes the code to catch them or at least re-raises them? Personally, I'd vote for the former as I don't think it's the responsibility of a library/package like inquirer to handle these exceptions at all, but then, I'm not really a python programmer, so maybe I'm missing something here.

Thanks

Mark

**Comment by magmax** [comment]
You are right.

See version 2.1.11: now you can call prompt with the new `raise_keyboard_interrupt` parameter in order to manage it if you wish. Default value is False in order to maintain backwards compatibility.

By the way... I usually think nobody is using inquirer, so it discourages me to improve it. Would you like to add to the README.md a new section about how do you use it and/or links to the packages you are importing it?

Thank you!

**Comment by mmrwoods** [comment]
Thanks @magmax, that's great, I'll update to 2.1.11 asap :-)

I'm currently just using inquirer with a custom command line app we use for managing aws cloudformation stacks. Unfortunately, it's not open source, so I can't add a reference to it in the readme, but FWIW, I've used inquirer to replace custom code to prompt for user input when the app is run in interactive mode (i.e. without all required options provided as command line arguments). We're prompting for input, confirming actions, asking users to select an option from a list, and asking users to select multiple options from a list using checkboxes.

I'm not really a Python programmer, having come mostly from the ruby world where I've used the tty gem for this kind of thing in the past. Inquirer is the nearest thing I've found for python, and so far is serving us very well.

Actually, come to think of it, another thing that struck me as odd and I quickly worked around was the way default values work when prompting for input.... Inquirer just prefills the field with the default, and users have to actually delete that value in order to override the default. I expected the default value to be shown in brackets or something like that, and if the user hit enter without typing anything that would mean accept the default, but if they wanted to override the default, they'd just type whatever value they wanted, without haing to delete the default value first. Here's some (horrible, because it's backwards compatible) code:

```
def prompt(message, default=None):
    # Inquirer's mechanism for handling defaults is a bit weird. It prefills
    # the text entry rather than dealing with users entering no value. Users
    # then need to delete the default value in order to enter a custom value.
    # So, we'll explicitly handle defaults so they work more conventionally.
    if default is not None:
        message = message + ' [{}]'.format(default)

    questions = [
        inquirer.Text(
            'text',
            message=message
        )
    ]
    answers = inquirer.prompt(questions)
    if answers is None:
        raise KeyboardInterrupt

    value = answers['text']
    if value == '' and default is not None:
        return str(default) # always return a string
    else:
        return value
```

Mark

**Comment by magmax** [comment]
Yes, I know what you say.

Despite we are used to do this way, I think using the brackets defaults is not so easy to understand. I've sawn people trying to understand what it means or rewritting the default value. So I thought this other way to show the default value. If you do not want it, just rewrite it.

Maybe in a future I would change it in the way you say. Currently not.

In addition, I've checked the number of people who downloaded inquirer last month: 0. This do not motivates me to change it beyond necessary :)

Thank you anyway.
