### ISSUE TITLE
Press arrow keys when handling the text input will crash on Windows platform

### ISSUE THREAD

**Issue by kentwelcome** [magmax/python-inquirer#198]
By running the example code on the Windows platform, it will crash when I press arrow keys (ex: ←, →, etc...).
```
import re

import inquirer
questions = [
  inquirer.Text('name', message="What's your name"),
  inquirer.Text('surname', message="What's your surname"),
  inquirer.Text('phone', message="What's your phone number",
                validate=lambda _, x: re.match('\+?\d[\d ]+\d', x),
                )
]
answers = inquirer.prompt(questions)
```

<img width="1229" alt="CleanShot 2022-07-22 at 11 38 42@2x" src="https://user-images.githubusercontent.com/959606/180357560-56fcaf7d-c2a7-4e56-bb7d-8c0c99943ad2.png">

The crash point is this line, the variable `pressed ` will be `None` on Windows platform.
https://github.com/magmax/python-inquirer/blob/786a5f7ffd2d6df04c4b20528fbab4b201f546af/src/inquirer/render/console/_text.py#L37

Python-inquirer version: 2.9.2
Python Version: 3.9.12 64-bit
OS: Microsoft Windows [Version 10.0.17763.3165]

**Comment by Cube707** [comment]
This is a issue with `v3.0.5` of the `readchar` libary used by inquery. Should be fixed with the new version of `readchar` that was released yesterday. Please update `readchar` and test again
