### ISSUE TITLE
multiline message blows up the UI

### ISSUE THREAD

**Issue by markfink** [magmax/python-inquirer#20]
I used a \n in the message of a choices list like I would do in inquirer.js. It displays fine at first but as soon as I move the cursor I prints out extra lines (see screenshot).

![image](https://cloud.githubusercontent.com/assets/33456/20718876/77fc2914-b65a-11e6-8a03-973a8ae9705b.png)

**Comment by magmax** [comment]
Python inquirer is not a full rewrite of inquirer.js in python; it is just inspired by inquirer.js.

If the \n is blowing up the ui, just remove it or use `.strip()`

Thank you anyway by the comment.
