### ISSUE TITLE
"Deutsche" is wrong in this context

### ISSUE THREAD

**Issue by Sofahamster** [magmax/python-inquirer#213]
https://github.com/magmax/python-inquirer/blob/741be401b9f39f1d016b4d7750b4d6dda8f32107/examples/located.py#L14

If you are referencing the german language, it is just "Deutsch", not "Deutsche".

**Comment by Cube707** [comment]
good find, thats a typo.

If you want to you can open a PR that, if not I will fix it in the next couple of days.
