### ISSUE TITLE
Proposal: new maintainer

### ISSUE THREAD

**Issue by staticdev** [magmax/python-inquirer#214]
[Cube707](https://github.com/magmax/python-inquirer/issues?q=is%3Aissue+is%3Aopen+author%3ACube707) has been doing a great job with updates from python-inquirer. If you agree I want to step out of maintenance of this project since I am over-commited to projects in Github. Would you like that?

**Comment by Cube707** [comment]
I just took over the `readchar` project and as it is closely related to this project (and caused a fair bit of issues here) I took the time to resolve the issues here. But as `readchar` is my first project with real users I don't feel ready to imeadiatly take on another responsibility. Sorry.

I am happy to help out though, especially with readchar related issues.

**Comment by staticdev** [comment]
@Cube707 would you be open then to be maintainer alongside me and see if it is ok for you?

**Comment by Cube707** [comment]
yes, that would be great

**Comment by staticdev** [comment]
@magmax could you also add him as a maintainer?

**Comment by magmax** [comment]
sure. Done!
