### ISSUE TITLE
How do we deploy the documentation?

### ISSUE THREAD

**Issue by Cube707** [magmax/python-inquirer#231]
@magmax 

How do we currently delpoy the documentation? `.github/workflows/documentation.yml` only creates a zip-file and attatches it to the action, so are you currently manually deploying it?

Should we create an automated process for that, so that changes will be autouploaded to the webserver?

**Comment by staticdev** [comment]
It is a rather simple thing to send to readthedocs.. explanation:

https://cookiecutter-hypermodern-python.readthedocs.io/en/2022.6.3.post1/guide.html#read-the-docs-integration

There is an example in this repo:

- https://github.com/staticdev/human-readable/blob/main/.github/workflows/tests.yml#L94
- https://github.com/staticdev/human-readable/blob/main/.readthedocs.yml

How-to:

**Comment by Cube707** [comment]
yes, but we are currently using magmax's webserver under [magmax.org/python-inquirer/](https://magmax.org/python-inquirer/), so the question is if we want to keep it there, if we want to autodeploy to that server, or if we want to switch to readthedocs

**Comment by Cube707** [comment]
deploying to read-the docs in the future
