### ISSUE TITLE
Phone number validation doesn't really work correctly

### ISSUE THREAD

**Issue by tombusby** [magmax/python-inquirer#25]
A UK phone number is of the format +44 1234 123456 (country area number). I only include the spaces here to illustrate the format.

It won't accept as valid even if you give the country code as 0044. I've also tried it with my Polish phone number and it won't accept that either.

I've just noticed that the regex is in the code sample itself:

```python
questions = [
  inquirer.Text('name', message="What's your name"),
  inquirer.Text('surname', message="What's your surname"),
  inquirer.Text('phone', message="What's your phone number",
                validate=lambda x, _: re.match('\d+', x),
                )
]
```
However, there's no value I seem to be able to give it that will pass validation. I haven't forgotten to import re.

**Comment by magmax** [comment]
I see.. You mean in the documentation. Good point. I'll try to fix it as soon as I could.

**Comment by tombusby** [comment]
I don't know exactly what the root cause is. All I know is the code sample in your README.md doesn't work.

**Comment by magmax** [comment]
should be already fixed.

**Comment by tombusby** [comment]
I've just tried the new code sample. Still doesn't work.

**Comment by tombusby** [comment]
Also, as an aside `inquirer.Confirm` blocks Ctrl+C but the other types don't.

**Comment by magmax** [comment]
It doesn't work to you because the fix is in the above code. Try this instead:
``` python
import inquirer
questions = [
  inquirer.Text('name', message="What's your name"),
  inquirer.Text('surname', message="What's your surname"),
  inquirer.Text('phone', message="What's your phone number",
                validate=lambda x, _: re.match('\+?\d[\d ]+\d', x),
                )
]
answers = inquirer.prompt(questions)
```

Please, if you think there is an issue with `inquirer.Confirm`, open another issue.

**Comment by drkvogel** [comment]
I have this problem too, nothing matches unless I set `validate=True`. I've tried various phone numbers. I even set the regex to `.*` and nothing matched.

**Comment by drkvogel** [comment]
I wondered if it was something to do with the shell and tried it in bash instead of zsh, but no dice. I'm on MacOS.

**Comment by AuHau** [comment]
Can you post the code?

**Comment by drkvogel** [comment]
```
  inquirer.Text('phone', message="What's your phone number",
                # validate=lambda _, x: re.match('\+?\d[\d ]+\d', x), # none of these return True
                # validate=lambda x: re.match('\+?\d[\d ]+\d', x),
                # validate=lambda _, x: re.match('.*', x),
                # validate=True,  # this works...
                # validate=lambda x, _: re.match('^.*$', x), # nope
                # validate=lambda x, _: re.match('\+?\d[\d ]+\d', x), # no
                # validate=lambda x, _: re.match('\d+', x), # no
                # validate=lambda x, _: re.match('.*', x) is not None,
                # validate=re.match('.*', x) is not None, # NameError: name 'x' is not defined
                # validate=lambda x, _: re.match('.*', _) is not None, # yep
                # validate=lambda x, _: re.match('\d+', _) is not None, # yep (with digits)
                # validate=lambda x, _: re.match('\+?\d[\d ]+\d', _) is not None, # yep (original regex)
                validate=lambda x, _: re.match('\+?\d[\d ]+\d', _), # also works, don't need `is not None`
  )
```

**Comment by drkvogel** [comment]
So the one that works is:

```python
validate=lambda x, _: re.match('\+?\d[\d ]+\d', _),
```

not:

```python
validate=lambda _, x: re.match('\+?\d[\d ]+\d', x)
```

from the example. Note that  `_` and `x` are swapped in the arguments to the lambda and the second argument to `re.match()` is `_`, not `x`.

**Comment by AuHau** [comment]
Ehm, `validate=True` means it is always valid, sooo nothing interesting there.
Otherwise, the `validate` function is called with signature `validate(previous_answers, current_value_of_current_question)`, therefore you are interested in the second argument ;-) I tried the current example in master and it worked as expected, that said it is not somehow advanced validation it just shows how it works...
