### ISSUE TITLE
Feature request: Extend validation to allow parsing of results

### ISSUE THREAD

**Issue by balanceofcowards** [magmax/python-inquirer#253]
Validation and parsing are often closely interrelated.

Right now, when I want to parse, e.g., a list of floating point numbers, it might look as follows:

```
questions = [inquirer.Text("number", message="Enter a list of floats"), validate=validate]
answer = inquirer.prompt(questions)
answer["number"] = parse(answer["number"]
```

The `validate` and `parse` functions will be very similar in this example, differing only in their return value. IMHO, this leads to unnecessary code duplication.

Currently, `validate` is expected to return a boolean value. Instead, the function signature could work as follows: If `validate` throws an exception, validation has failed. In all other cases, the answer is replaced by the return value of `validate`.

**Comment by Cube707** [comment]
this request is similar to #241 where a preprocessor option was suggested. As discussed there, executing code "magically" inside the libary ist hard to make save/maintain on our end and makes it harder to debug on the programmers end. 

Problems like this are specific to any particular usecase and should be handled on a per case baisis by the programmer and not internaly by the function (even if "internaly" means calling programmer defined code...)

---

And here are a few comments comming to mind for your example:

`validate` and `parse` should be kept seperately as they are two very seperate things. Using the same function for both makes the code much harder to read and maintain. If you have a case where it's inteducing code-duplication, use a third function for the duplicate code:

```python
def str2float(num):
    return float(num)
def parse(str):
    return str2float(str)
def validate(str):
    try:
        return bool(str2float(str))
    except:
        return False
```

or use anonymous functions:

```python
validate=lambda _,x: bool(parse(x))
```

**Comment by balanceofcowards** [comment]
Hm, yeah, I can see that point. Agreed, then.

Minor nitpick, though: The lambda function works that way only if the try/except clause is in parse, already. Still a good idea -- I'm gonna work that way. Thanks for the hint!

**Comment by Cube707** [comment]
> Minor nitpick, though: The lambda function works that way only if the try/except clause is in parse, already. Still a good idea -- I'm gonna work that way. Thanks for the hint!

Actually, inquire handles exceptions in `validate` as failed validation. But yes, lambda function only work in super simple cases 

(also `0` will be detected as invalid number with this, as `bool()` casts it to `False`)
