### ISSUE TITLE
Checkbox: Have an option to select all and reset all selection

### ISSUE THREAD

**Issue by palash247** [magmax/python-inquirer#267]
The ability to select every option or clear the current selection with a single keystroke would be fantastic. Something like this is in inquirer.js, here's the [feature request](https://github.com/SBoudrias/Inquirer.js/issues/308). Additionally, we can specifically mention this feature in the prompt. Please assign it to me if accepted as an enhancement.

**Comment by Cube707** [comment]
defnetly an interesting idea. If wou want to, go ahead and open a PR for this.

I would also consider <kbd>CTRL+A</kbd> ... as opions that are maybe more inline with other programs?

**Comment by palash247** [comment]
Please assign it to me again, I removed my self by mistake.

**Comment by palash247** [comment]
Thanks. Also, can you please review #257

**Comment by Cube707** [comment]
closed by https://github.com/magmax/python-inquirer/pull/275
