### ISSUE TITLE
theme customization

### ISSUE THREAD

**Issue by ProvoK** [magmax/python-inquirer#29]
Hello there, 
first of all, thanks for this project! I'm using it and it saves me a lot of time.
Besides that, i think a quite important feature is missing: customization.

I'm currently developing a solution to address that, aka choose color/symbols, at runtime.
A simple usage of what I'm developing would be
```
import inquirer

# question definitions 

class MyTheme(inquirer.Theme):
    # redefine properties

inquirer.prompt(questions, theme=MyTheme) 
```

I would happily contribute to this project, but i'm new to opensource and i can't see a 'contribute readme', so I'm posting here, hoping this feature would be welcome.

**Comment by magmax** [comment]
Well, you did it well: by writting the patch and sending it to me to evaluate it :)

Thank you for your contrib!

Maybe we both can add that readme and even a section "who isuses using it"...
