### ISSUE TITLE
Choices should allow for a separate list of display names

### ISSUE THREAD

**Issue by juanrgon** [magmax/python-inquirer#31]
The choices list for Checkbox and List questions should allow for either an additional `display` argument, or accept a a list of lists, where the first element of list item is the value to return and the second is what to display in the list of choices

**Comment by magmax** [comment]
Choices can be a function returning an array.
In addition, I'm not sure, but I swear that it can return an Object array and, maybe, it will render the object str() string.
But I like the idea, anyways.

**Comment by magmax** [comment]
I tried it and it is supported.
Choices must be an array containing tuples. The first element is the label and the second one, the value.
Example: `choices=[('Small', 1), ('Micro', 2)]`

Does this fit your requirements?

**Comment by juanrgon** [comment]
That's perfect!

I don't think this is [documented](http://python-inquirer.readthedocs.io/en/latest/usage.html#choices)?

**Comment by magmax** [comment]
Yes, it is:
> If any of the list values is a pair, it should be a tuple like: (label, value). Then the label will be shown but the value will be returned.
https://github.com/magmax/python-inquirer/blob/master/docs/source/usage.rst

**Comment by juanrgon** [comment]
Totally missed it. This is great. Thank you

**Comment by magmax** [comment]
you're welcome.
The idea was great, but someone had the same idea before ;)
