### ISSUE TITLE
2.2.0 displaying selection next to prompt

### ISSUE THREAD

**Issue by jonpurdy** [magmax/python-inquirer#33]
I see that the behaviour of the prompt has changed with 2.2.0: now, the name of the selection is displayed next to the prompt whereas <2.2.0 this didn't occur.

Is there an option to toggle this off?

2.1.11:
<img width="445" alt="2 1 11" src="https://user-images.githubusercontent.com/7793621/33018785-c514f504-cdc5-11e7-8b99-30deb1f52218.png">
2.2.0:
<img width="557" alt="2 2 0" src="https://user-images.githubusercontent.com/7793621/33018786-c5210150-cdc5-11e7-89cc-bf7ba03ddf2a.png">

Thanks in advance for the reply!

**Comment by magmax** [comment]
I'm afraid it is not. But it is not a bad idea.

Sorry for being too late answering...

**Comment by staticdev** [comment]
Closing this for now, I will focus on bugs and type-annotations.
