### ISSUE TITLE
Installing on Windows running python 3.5

### ISSUE THREAD

**Issue by wvankuyk** [magmax/python-inquirer#35]
Collecting inquirer
  Using cached inquirer-2.2.0-py2.py3-none-any.whl
Collecting blessings>=1.6 (from inquirer)
  Downloading blessings-1.6.1-py3-none-any.whl
Collecting readchar==0.7 (from inquirer)
  Using cached readchar-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\r611348\AppData\Local\Temp\2\pip-build-sxwyd3b1\readchar\setup.py", line 15, in <module>
        long_description=read_description(),
      File "C:\Users\r611348\AppData\Local\Temp\2\pip-build-sxwyd3b1\readchar\setup.py", line 9, in read_description
        return fd.read()
      File "C:\Users\r611348\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2462: character maps to <undefined>

**Comment by kingeke** [comment]
I'm getting the same error.. any solution or alternative ??

**Comment by mikevaleriano** [comment]
Python 3,6,4, same issue on Windows 10.

**Comment by matAlmeida** [comment]
I'm running into the same problem. Looking for some way to solve i found some people telling to run `pip install --upgrade setuptools`, i did it but still the same error message.

I'm using `Python 3.6.5`. I installed on my Ubuntu running `Python 3.5.2` and it installed clean

![image](https://user-images.githubusercontent.com/12724212/41576768-9298cee4-735f-11e8-96a5-16858864d4ec.png)

**Comment by Bayees** [comment]
`pip install inquirer
Collecting inquirer
  Using cached https://files.pythonhosted.org/packages/bd/b8/0b04f23f7870f96c81bdf9b9863c12985bec0f2738218bcfc67842be4ae8/inquirer-2.2.0-py2.py3-none-any.whl
Collecting readchar==0.7 (from inquirer)
  Using cached https://files.pythonhosted.org/packages/61/a9/d552ab5bb2978b609a0acc917427fb0230ac923d92e32b817ef79908f6e3/readchar-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\CBAY\AppData\Local\Temp\pip-install-t9nf3t4u\readchar\setup.py", line 15, in <module>
        long_description=read_description(),
      File "C:\Users\CBAY\AppData\Local\Temp\pip-install-t9nf3t4u\readchar\setup.py", line 9, in read_description
        return fd.read()
      File "C:\Users\CBAY\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2462: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\CBAY\AppData\Local\Temp\pip-install-t9nf3t4u\readchar\`

Same error on Windows 10, with python 3.6.4 and setuptools 39.2.0

**Comment by Newtt** [comment]
same error on Ubuntu server latest version.... kind of annoying...

**Comment by CITGuru** [comment]
Currently, you won't be able to use python-inquirer on Windows, since it depends on blessings which is not supported on Windows. A good alternative is [PyInquirer](https://github.com/CITGuru/PyInquirer/). You can check it out.

**Comment by AuHau** [comment]
I am closing this issue. For more information see #63
