### ISSUE TITLE
Fails to install on Python 3.6

### ISSUE THREAD

**Issue by danmichaelo** [magmax/python-inquirer#36]
```
Collecting readchar==0.7 (from inquirer->almar==0.7.2)
  Using cached readchar-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-33aeocmc/readchar/setup.py", line 15, in <module>
        long_description=read_description(),
      File "/tmp/pip-build-33aeocmc/readchar/setup.py", line 9, in read_description
        return fd.read()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2461: ordinal not in range(128)
```

Per https://github.com/magmax/python-readchar/issues/26 , this seems to have been fixed in 0.1.0 (or before?).

Note: The version that follows 0.7 is 0.0.8, then 0.0.9 and 0.1.0. Ref: https://pypi.org/project/readchar/#history

* [Version 0.0.8](https://travis-ci.org/magmax/python-inquirer/builds/340541258) fails with Python 3.3
* [Version 0.0.9](https://travis-ci.org/magmax/python-inquirer/builds/340549525) fails with Python 3.3
* [Version 0.1.0](https://travis-ci.org/magmax/python-inquirer/builds/340521472) fails with Python 2.7

**Comment by Newtt** [comment]
still not working sadly....

`Collecting inquirer
  Using cached https://files.pythonhosted.org/packages/bd/b8/0b04f23f7870f96c81bdf9b9863c12985bec0f2738218bcfc67842be4ae8/inquirer-2.2.0-py2.py3-none-any.whl
Collecting blessings>=1.6 (from inquirer)
  Using cached https://files.pythonhosted.org/packages/03/74/489f85a78247609c6b4f13733cbf3ba0d864b11aa565617b645d6fdf2a4a/blessings-1.7-py3-none-any.whl
Collecting readchar==0.7 (from inquirer)
  Using cached https://files.pythonhosted.org/packages/61/a9/d552ab5bb2978b609a0acc917427fb0230ac923d92e32b817ef79908f6e3/readchar-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gzmybqyb/readchar/setup.py", line 15, in <module>
        long_description=read_description(),
      File "/tmp/pip-build-gzmybqyb/readchar/setup.py", line 9, in read_description
        return fd.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2461: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gzmybqyb/readchar/`

**Comment by purohit** [comment]
@danmichaelo What's your recommended solution to this problem for now?

**Comment by magmax** [comment]
Give me a couple of weeks yo fix it, please. Maybe less

--
perdona que sea escueto... Te estoy escribiendo desde el móvil

**Comment by danmichaelo** [comment]
Woha, seems to work now! Thanks alot!
