### ISSUE TITLE
Feature Suggestion: allow "other" option in list input

### ISSUE THREAD

**Issue by queengooborg** [magmax/python-inquirer#370]
_This was also requested for `inquirer.js` -- see https://github.com/SBoudrias/Inquirer.js/issues/1198_

I'm utilizing `inquirer` for a command line script to generate pull requests (including titles and descriptions) for [MDN's BCD repository](https://github.com/mdn/browser-compat-data), and first of all, I must say: kudos to the dev team here!  I've always enjoyed the original `inquirer.js` for CLI prompts, and am happy to see a port to Python available!

As a part of one of my questions within the script, I inquire a `reason` from the user, which is a list of preset entries, as well as an "Other" entry.  In this script, I then check to see if "Other" was selected, and if so, prompt the user for a text input to describe the `reason`.  This looks something like so:

```py
reason = inquirer.list_input(
  message="Why is this feature being removed?",
  choices=['Irrelevant', 'Non-Interface', 'Other']
)
if reason == "Other":
  reason = inquirer.text("Why is this feature being removed?")
```

```
[?] Why is this feature being removed?: Other
   Irrelevant
   Non-Interface
 > Other

[?] Why is this feature being removed?: I just don't like this feature... >:(
```

I think it would be nice to have an `other` option (or something similar), that adds an option to the end which doubles as a text input, like so:

```py
reason = inquirer.list_input(
  message="Why is this feature being removed?",
  choices=['Irrelevant', 'Non-Interface'],
  other="Other Reason" # default: false, setting to "true" will add "Other"
)

# ...or...

reason = inquirer.list_input(
  message="Why is this feature being removed?",
  choices=['Irrelevant', 'Non-Interface', inquirer.list_choice_other('Other Reason')],
)
```

```
[?] Why is this feature being removed?: Irrelevant
 > Irrelevant
   Non-Interface
   Other

...or...

[?] Why is this feature being removed?: 
   Irrelevant
   Non-Interface
 > Other: 

...or...

[?] Why is this feature being removed?: I just don't like this feature... >:(
   Irrelevant
   Non-Interface
 > Other: I just don't like this feature... >:(
```

**Comment by Cube707** [comment]
Does #256 implement what your looking for? This is already merged

**Comment by queengooborg** [comment]
Oh awesome, I hadn't seen this PR!  I thought I searched through PRs as well, whoops -- I didn't see anything in the [documentation](https://python-inquirer.readthedocs.io/en/latest/) regarding this option (note: the magmax.com URL is a 404)!

**Comment by Cube707** [comment]
Yea ist a mess too look through PRs with all the dependabot stuff...

And good to know that the documentation is down, i will need to fix that. (See #)
