### ISSUE TITLE
Is there a way to specify a key per item ?

### ISSUE THREAD

**Issue by stuaxo** [magmax/python-inquirer#385]
I'm using inquirer to display a menu, that I'll use when debugging a black-screen issue on my computer, can I give each item in the list a hotkey ?

(Basically - when it's working I want to see the menu, but for the other time, it's a quick way to reboot and log a particular message depending on which key I press)

**Comment by Cube707** [comment]
no, but you can create this on your own using the `readchar` libary which inquirer is based on

**Comment by stuaxo** [comment]
Thanks for getting back to me promptly, this is only a for a throwaway thing I'm overengineering so I'll hop onto another library.
