### ISSUE TITLE
Validation of group of Questions

### ISSUE THREAD

**Issue by AuHau** [magmax/python-inquirer#39]
Hey there,

First of all thanks for great tool!

I am wondering how to do validation of a group of questions. The use-case is pretty simple if I ask for login credentials (typical username & password) in two separate questions I can put validation on the later one and access the value of the first one through `answers`. So far, so good. 
The issue is that if the validation fails, the user can change only the value of the second Question not the first one. 

Is there some way how to rollback to the first Question?

Thanks

**Comment by magmax** [comment]
I'm afraid that is not the intention of the validation.

The correct way to do that is:

```
questions = ...
while True:
     answers = prompt(...)
     if valid_credentials(answers):
          break
```

Thank you very much and sorry for the delay.
