### ISSUE TITLE
Cannot move cursor when running a list prompt in a docker container

### ISSUE THREAD

**Issue by rrei** [magmax/python-inquirer#40]
I'm trying to use a list prompt, and while it does work properly with the arrow keys on my Ubuntu 16.04 machine, the cursor doesn't move at all if I run the code below inside a docker container. I can still press return to get a value from the prompt, but since the cursor doesn't move it will always give me the first option. Any clues? 

```
import inquirer

inquirer.prompt([inquirer.List(name="q", message="foo", choices=range(5))])
```

I'm guessing this may have something to do with docker overriding some keyboard or terminal event handlers, but this far exceeds my knowledge.

I really love this library, however this is a deal breaker for me and I can't use it until this is fixed... :cry: 

PS: I've just checked and the same behavior occurs with `inquirer.Checkbox` prompts.

**Comment by magmax** [comment]
The problem here may be the terminal.

Have you tried running: "TERM= ./your_program.py"?

**Comment by chrisbrownie** [comment]
I am seeing this behaviour as well, regardless of `TERM=` value.

**Comment by rrei** [comment]
> The problem here may be the terminal.
> 
> Have you tried running: "TERM= ./your_program.py"?

Apologies for taking so long to respond...  :(
I just tried running my example in a `python:slim` container and it worked!

```
user@host ~/scratch$ docker run --rm -ti python:slim bash                                                                                                                        root@27f10e4da402:/# pip install inquirer
Collecting inquirer
  Downloading https://files.pythonhosted.org/packages/97/58/fa0de1a822864673ccd9ed20fc309f869de48216527c6f0d47c18f2e4be7/inquirer-2.6.3-py2.py3-none-any.whl
Collecting readchar==2.0.1 (from inquirer)
  Downloading https://files.pythonhosted.org/packages/ef/f3/50cc9199733bf91f3c140150752a6430d8b785f9d22a31dcae721edb0b9a/readchar-2.0.1-py3-none-any.whl
Collecting python-editor==1.0.4 (from inquirer)
  Downloading https://files.pythonhosted.org/packages/c6/d3/201fc3abe391bbae6606e6f1d598c15d367033332bd54352b12f35513717/python_editor-1.0.4-py3-none-any.whl
Collecting blessings==1.7 (from inquirer)
  Downloading https://files.pythonhosted.org/packages/03/74/489f85a78247609c6b4f13733cbf3ba0d864b11aa565617b645d6fdf2a4a/blessings-1.7-py3-none-any.whl
Collecting six (from blessings==1.7->inquirer)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: readchar, python-editor, six, blessings, inquirer
Successfully installed blessings-1.7 inquirer-2.6.3 python-editor-1.0.4 readchar-2.0.1 six-1.12.0
root@27f10e4da402:/# python
Python 3.7.4 (default, Aug 14 2019, 12:19:22) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import inquirer
>>> inquirer.prompt([inquirer.List(name="q", message="foo", choices=range(5))])
[?] foo: 3
   0
   1
   2
 > 3
   4

{'q': 3}
>>> inquirer.__version__
'2.6.3'
>>> 
```

**Comment by michelsciortino** [comment]
this happens also outside of a docker container (win 10, powershell 7.2.1)

**Comment by CHOPPER9** [comment]
> this happens also outside of a docker container (win 10, powershell 7.2.1)

Have you found the solution?
