### ISSUE TITLE
Ascii Issue

### ISSUE THREAD

**Issue by Longshotpro2** [magmax/python-inquirer#43]
This is all a learning experience for me so the answer may be obvious and I am just missing it.

If I create a list as such:
```
LangQuestion = [
    inquirer.List('lang',
                  message="Select Language",
                  choices=['English', 'Français', 'Deutsche'],
              ),# ç
]

answers = inquirer.prompt(LangQuestion)

pprint(answers)
```
It breaks due to UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)

However anywhere else in my project where I reference Français and does not involve using inquirer it works fine. Is there a way to expand the ascii to accommodate such characters? I thought UTF-8 would cover all of it to begin with but again this is outside of my realm of knowledge.

Thank you for your time!

**Comment by AuHau** [comment]
Well for me, your example works fine, so the big question is what version of Python you run?

**Comment by magmax** [comment]
Hello,

This seems to be a python2 problem. It is fixed in python3.

Anyway, you can add `# encoding: utf-8` to the file headers and it should work (well... you must save it as UTF-8 in your editor too).

More information: https://stackoverflow.com/questions/10589620/syntaxerror-non-ascii-character-xa3-in-file-when-function-returns-%C2%A3

**Comment by AuHau** [comment]
Hmm looking at your solution, I would quiet object that it is a good one.
I don't think library should do such operations, it should be the user's responsibility to provide valid input, which in this case means properly decoded strings in case of Python.
What if for example they use different encoding, I know that in these days it is not really common to use something else then UTF-8, but it is possibility...

But it is your call 😉
