### ISSUE TITLE
[Question] Does it support to make required input?

### ISSUE THREAD

**Issue by aprilahijriyan** [magmax/python-inquirer#435]
Hi,

Based on the documentation on https://python-inquirer.readthedocs.io/en/latest/usage.html#question-arguments. This package only supports hiding input using the `ignore` param.

It would be great, if it had the required input feature. Say adding the `required=True` param to the `Question` object to enable this feature.

So, this feature requires the user to fill in the input value.

April

**Comment by Cube707** [comment]
as per #327 you can lock choices, making it imposible tzo de-select them. Does this help you?

**Comment by Cube707** [comment]
sorry that the documentations is not up to date
