### ISSUE TITLE
Select All Option For Checkbox

### ISSUE THREAD

**Issue by srezasm** [magmax/python-inquirer#468]
Is there any way to add a "select all" button to the `Checkbox` list? If not please implement it.

**Comment by Cube707** [comment]
no there is not. additional keyboard shortcuts could be implemented and PRs for this would be welcome

**Comment by julianaklulo** [comment]
Version `3.1.0` implemented shortcuts to select all (`Ctrl+A`), deselect all (`Ctrl+R`) and invert selection (`Ctrl+I`).
