### ISSUE TITLE
Handling many choices in List/Checkbox

### ISSUE THREAD

**Issue by AuHau** [magmax/python-inquirer#49]
If there is high number of choices in List or Checkboxes the behavior is far from optional. The list will overflow the screen and navigation becomes practically impossible.

I suggest limiting the size of "scrollbox" to a certain number of lines and scroll through the box when person navigate to the end/beginning. 

Also, I would suggest adding filtering/auto-suggesting feature, which would allow the user to start typing while in the List/Checkbox question, which would filter out the choices displayed.

@magmax do you think the proposed solution&feature is feasible? If so, I could work on it, if you would accept the PR...

**Comment by magmax** [comment]
I have written a fix for this at 204f566e08e3b09ab0eca2dd77535458b6bdab9d, but it has some visual problems.

The inicial solution was too easy, but I'm not sure about how to solve the problems and how to combine it with carousel.

Any ideas?

**Comment by trunet** [comment]
> I have written a fix for this at [204f566](https://github.com/magmax/python-inquirer/commit/204f566e08e3b09ab0eca2dd77535458b6bdab9d), but it has some visual problems.

It's not implemented for checkbox.

**Comment by AuHau** [comment]
Should be solved with #72
