### ISSUE TITLE
WIN10 AttributeError: module 'inquirer' has no attribute 'Checkbox'

### ISSUE THREAD

**Issue by ICYPOLE** [magmax/python-inquirer#54]
Testing examples, there are problems like this: 
_An error was found, but returning just with the version: No module named '_curses'
Traceback (most recent call last):
  File "D:/miraclebaby/rua.py", line 10, in <module>
    inquirer.Checkbox('interests',
AttributeError: module 'inquirer' has no attribute 'Checkbox'_

I am just a beginner for python : (

WIN10 
Python 3.7

**Comment by AuHau** [comment]
As mentioned in #12 python-inquirer does not support Windows platform at the moment (and most probably that won't change in close future)

**Comment by AuHau** [comment]
I am closing this issue. For more information see #63
