### ISSUE TITLE
path missing as shortcut

### ISSUE THREAD

**Issue by victormachadoperez** [magmax/python-inquirer#542]
I was trying to use path as a shortcuts when I realized it was not available , but yet it is implemented in shortcuts.py
Is it missing in the __init__.py... or I'm missing something?

Thanks

**Comment by Cube707** [comment]
Yes thats an oversight. Feel free to open a PR for this, or I will do it myself in the coming weeks

**Comment by victormachadoperez** [comment]
Hi there, the issue is already fixed and merged. 
But for some reason I cannot access to inquirer.path(...) in my code. 
Using inquirer v3.2.4

**Comment by Cube707** [comment]
I will look through the dependabot PR's and make a release later today
