### ISSUE TITLE
problem in importing _curses

### ISSUE THREAD

**Issue by K1LLER0M** [magmax/python-inquirer#56]
When you import inquirer module, the terminal tells me that there is an error
"no module _curses"

**Comment by dharif23** [comment]
Sorry to disappoint you here. python-iquirer doesn't support _curses. I not sure which operating system you are using but if it is windows then be sure of that it won't support this module. Hope that helps.

**Comment by K1LLER0M** [comment]
I'm using windows 10 and i don't even know this _curses module tho

**Comment by magmax** [comment]
I'm afraid this is legacy code from a try to support it. I will remove it in a couple of days.

**Comment by AuHau** [comment]
Hmm if I see it correctly, then this issue is solved with https://github.com/magmax/python-inquirer/commit/a99b557268b05ca618411a6a75f74ff0c20ca069

Hence I am closing this issue, but feel free to reopen it if the problem persist.
