### ISSUE TITLE
Programmatically making selections for testing

### ISSUE THREAD

**Issue by tterb** [magmax/python-inquirer#60]
First off, I just want to say that I think this package does a great job of allowing for more interactive and accessible python CLI's.  
Though I've spent some time attempting to simulating keypresses or programmatically make selections within a unit-test and have been unsuccessful so far. Is there a method for accomplishing this that I'm missing?

**Comment by AuHau** [comment]
Hmm do you mean for testing python-inquirer itself or your own app?

I don't know about a solution on OS level, but @magmax used mocking approach for his tests. I would recommend you to study the integration tests of this package: https://github.com/magmax/python-inquirer/tree/master/tests/integration/console_render

**Comment by AuHau** [comment]
Since no additional info or asks were presented, I am closing this, but feel free to shoot more questions!
