### ISSUE TITLE
New line printed every time option is selected

### ISSUE THREAD

**Issue by YoussefEssalhi** [magmax/python-inquirer#604]
Whenever I use the `python-inquirer` library in my project, it prints a new line every time I select an option.
This behavior is unexpected as I expect the output to stay on the same line unless a new line is deliberately printed.

**The Code :**

![image](https://github.com/user-attachments/assets/d676e5a1-dfd3-449e-bf4f-8d2ee84ae28c)

**The Output :**

![image](https://github.com/user-attachments/assets/c1424c38-9459-4e21-9fc1-abd611f5bfc1)

**I Expect this output :**

![image](https://github.com/user-attachments/assets/6e78b027-ca8c-4d75-aac7-9fdd4eaefbe0)

**Comment by Cube707** [comment]
Hm, I can understand why you want to control this yourself. instead of it being decided for you. But this would be a breaking change that might affect existing projects in a bad way, so I am undecided if I want to change it

**Comment by Cube707** [comment]
as shown in https://github.com/magmax/python-inquirer/pull/605#issuecomment-2230383997, this breaks to much existing behavior.
