### ISSUE TITLE
List & CheckBox are limited to 13 elements

### ISSUE THREAD

**Issue by butoibogdan** [magmax/python-inquirer#617]
Hello
If I select more than 13 items and set them in the list or checkbox, the maximum number displayed in the console is 13.

 servers = [
        inquirer.List('servers',
                      message="Choose Servers",
                      choices=["Switch1", "Switch2", "Switch3", "Switch4", "Switch5", "Switch6", "Switch7",
                               "Switch8", "Switch9", "Switch10", "Switch11", "Switch12", "Switch13", "Switch14",
                               "Switch15", "Switch16", "Switch17", "Switch18", "Switch19", "Switch20", "Switch21",
                               "Switch22", "Switch23", "Switch24", "Switch25", "Switch26", "Switch27", "Switch28",
                               "Switch29", "Switch30", "Switch31", "Switch32", "Switch33", "Switch34", "Switch35",
                               "Switch36", "Switch37", "Switch38", "Switch39", "Switch40"],
                      )
    ]

Choose Servers: 
 > Switch1
   Switch2
   Switch3
   Switch4
   Switch5
   Switch6
   Switch7
   Switch8
   Switch9
   Switch10
   Switch11
   Switch12
   Switch13

Thanks

**Comment by Cube707** [comment]
You did realise you can scroll though?

`inquire.rendere.console.base.MAX_OPTIONS_DISPLAYED_AT_ONCE` controlls this, 13 was chosen arbitrarily as it just seemed right.

**Comment by butoibogdan** [comment]
Thanks I didn't realize that exists scroll :))
Thanks
