### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by AuHau** [magmax/python-inquirer#63]
As mentioned in README, currently Windows is not supported because python-inquirer depends on `blessing` package, which does not support Windows at this moment.

There is some hope that this will change in the future: https://github.com/erikrose/blessings/issues/21

This issue is here to track progress on this problem.

**Comment by MasterEric** [comment]
It appears that there is a fork of `blessing`, called `blessed`, that supports Windows:

https://github.com/jquast/blessed

**Comment by vvstepanov** [comment]
How come windows isnt supported after the Unix compatible update? (happened some time this year)

**Comment by AuHau** [comment]
If somebody would be interested to try to integrate `blessed` as a replacement for `blessing` and would achieve full functionality, I think we would be open to merging such a patch!

**Comment by C0D3D3V** [comment]
I get the same test results when I replace all blessings with blessed. Can someone explain to me why we're not just doing this?

**Comment by C0D3D3V** [comment]
Here is the setup, how it works under Windows
unistall inquirer with pip
replace every occurrence of blessing  with blessed.
run python setup.py build
run python setup.py install
install windows-curses with pip

**Comment by realgam3** [comment]
> If somebody would be interested to try to integrate `blessed` as a replacement for `blessing` and would achieve full functionality, I think we would be open to merging such a patch!

Done :)

**Comment by AuHau** [comment]
Closed via #91 
Thanks @realgam3 !

**Comment by realgam3** [comment]
> Closed via #91
> Thanks @realgam3 !

Now I'm waiting for a new version :)
