### ISSUE TITLE
Vim keys (Could you add them, please)

### ISSUE THREAD

**Issue by sergey-samoylov** [magmax/python-inquirer#637]
It would be nice, if in addition to "arrow-keys navigation" there would be Vim-keys:
j - down
k - up
l - select choice (that is lower cased "L", not capital "I" of course)

This inquirer is nice and pretty text-nav tool, and lots of folks out there use Vim - one of the best, if not THE best text and code editors. So, such feature would add to inquirer more usability.

Thank you for this project. Like it!

**Comment by polirritmico** [comment]
Hi, `h`, `j`, `k`, `l` are like second nature for long time vim-like keymaps users, so using the arrows keys feels really strange.

I've made a PR to address this #652.

Thanks!

**Comment by Cube707** [comment]
same as with other request of this kind, adding one specific key-set only opens the discussion why not other key-sets, see https://github.com/magmax/python-inquirer/pull/560#issuecomment-2168153534
