### ISSUE TITLE
inquirer text multiline

### ISSUE THREAD

**Issue by pyinstallerbaggins** [magmax/python-inquirer#642]
When using multiline with completer=True. it stops using completer after the  1st or second entry.

Also, I am pressing 'ENTER' after each entry to get to the next line

![image](https://github.com/user-attachments/assets/40e041e0-cf2e-4199-9a28-e96148ce4ee2)

**Comment by Cube707** [comment]
multi-line is generally not supported, see #26 and related.

the completer probably works fine, it's output just gets override. But without a detailed, reproducible issue, guessing is all I can do.

**Comment by Cube707** [comment]
closing as there is not enough info to reproduce
