### ISSUE TITLE
2.5.2 publish

### ISSUE THREAD

**Issue by joeyism** [magmax/python-inquirer#65]
I see that there's a `2.5.2` tag, but I'm unable to install it with `pip3`. On pip3, it says the latest is `2.5.1`. Are there plans to publish `2.5.2` onto pypi?

**Comment by AuHau** [comment]
Hmm, this tag seems a bit odd because it is not associated with a commit that is not on the master branch. Hence I would suggest to ignore it.

I hope in following weeks I will release the next version.

**Comment by SupermanIsEvious** [comment]
Any updates on a new version? 2.5.2 carries a change which allows for limiting the scrollbox size of long lists, which is a very desirable change.

**Comment by ivanhercaz** [comment]
@joeyism @SupermanIsEvious, new versions released!

Check [2.6.0](https://github.com/magmax/python-inquirer/releases/tag/2.6.1) and [2.6.1](https://github.com/magmax/python-inquirer/releases/tag/2.6.1)

**Comment by SupermanIsEvious** [comment]
Hey @ivanhercaz 
It seems there's a problem with 2.6.1. 
```python
>>> import sys
>>> print('Python %s on %s' % (sys.version, sys.platform))
Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
>>> import inquirer
An error was found, but returning just with the version: No module named 'editor'
>>> inquirer.prompt
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: module 'inquirer' has no attribute 'prompt'
```
It looks like you forgot to list `python-editor` in your [dependency list](https://github.com/magmax/python-inquirer/blob/master/setup.py#L70).

**Comment by ivanhercaz** [comment]
Hi @SupermanIsEvious! 
I haven't contributed to the Inquirer code yet, but I will check it and try to fix it :) Although it is possible that @AuHau knows something about it.

**Comment by SupermanIsEvious** [comment]
@ivanhercaz Ah, my bad! I assumed you were a contributor since you knew about the new version so quickly.

I'm happy to do it as well.

**Comment by AuHau** [comment]
Sorry guys, my bad. Put the dependency to `requirements.txt` but forgot to place it to `setup.py`. That is what happens when you duplicate stuff - you forget to update it everywhere 😞 
New version is being released as I write this.
