### ISSUE TITLE
Add quick navigation options

### ISSUE THREAD

**Issue by ag0r** [magmax/python-inquirer#68]
It would be really nice to be able to quickly jump to a line number or something for List prompts that have many options.

**Comment by AuHau** [comment]
This is fixed with https://github.com/magmax/python-inquirer/pull/52 but I am afraid, that it was still not released. I should have some time in upcoming days to put into this project, soooo maybe there will be release soon :-)

**Comment by AuHau** [comment]
Sorry, wrong issue :-D 

Hmmm, yeah handling of List prompts with many options is currently far from optimal, I believe that this is related to #49 so please if you some input put there ;-) I am closing this for duplicate.

**Comment by AuHau** [comment]
@ag0r can you please describe what sort of behavior you mean? I am not sure if I completely understand your proposal. Remember that now there is only limited number of options visible...
