### ISSUE TITLE
python-inquirer does not work on OSX

### ISSUE THREAD

**Issue by grimnight** [magmax/python-inquirer#8]
Up and down arrows and enter do not work in List or Checkbox.
Checkbox responds to space bar.
On enter Password simply adds a star.
All other examples seem to work just fine.

**Comment by magmax** [comment]
Which version of readchar are you using? You can check it with ``pip freeze``

Thank you!

**Comment by grimnight** [comment]
inquirer==2.1.3
readchar==1.1.0

**Comment by magmax** [comment]
Please, just as bypass, use readchar 0.7.

I will fix this as soon as I could.

**Comment by grimnight** [comment]
Just to verify, 0.7 works on OSX.

**Comment by berdario** [comment]
This is an issue on Linux as well

Ubuntu 15.04, Python3.4 installed from [Nix](https://nixos.org/nix/)

(and indeed, with readchar 0.7 the problem doesn't appear either)

**Comment by magmax** [comment]
This should be fixed right now. Isn't it?

**Comment by AuHau** [comment]
I believe this works at the moment, hence I am closing this issue. Feel free to reopen if problems persist.
