### ISSUE TITLE
Class Text doesn't execute functions

### ISSUE THREAD

**Issue by mareckii** [magmax/python-inquirer#83]
field default doesn't execute function like message,
 instead of execute shows string representation of function:
'<function getDefaultLogin at 0x10c9bee60>'

**Comment by yardensachs** [comment]
Same issue, looks like it's by design?

https://github.com/magmax/python-inquirer/blob/c1b3bc776cec72b5039068ecbac509ce90d2e123/inquirer/questions.py#L141-L147

**Comment by mareckii** [comment]
Documentation says function is supported:
https://github.com/magmax/python-inquirer/blob/c1b3bc776cec72b5039068ecbac509ce90d2e123/docs/source/usage.rst#L83-L94

**Comment by jmrubio** [comment]
The issue was introduced by #62

**Comment by jmrubio** [comment]
Created a pull request for this #88

**Comment by fleytman** [comment]
Sorry. This is the wrong link.
