### ISSUE TITLE
Ignore example

### ISSUE THREAD

**Issue by staticdev** [magmax/python-inquirer#94]
It would be very nice to have a ignore example.

I have a list of four questions: two Confirm questions and two Text after each Confirm. I want to prompt the Text questions only if you answered yes to the previous. How would you do that using python-inquirer?

I've searched the whole repo and documentation and didn't find one. Could you add one please?

**Comment by ZhymabekRoman** [comment]
> It would be very nice to have a ignore example.
> 
> I have a list of four questions: two Confirm questions and two Text after each Confirm. I want to prompt the Text questions only if you answered yes to the previous. How would you do that using python-inquirer?
> 
> I've searched the whole repo and documentation and didn't find one. Could you add one please?

Can you show a reproducible example?

**Comment by staticdev** [comment]
Hypothetical example. Eg.
1. Confirm: do you like coffee?
2. Confirm: do you really love coffee?
3. Text: describe when do you drink coffee during the day. (ignored if 2 is false)
4. Text: describe what happens why you when you stay a whole day without coffee (also ignored if 2 is false)

**Comment by magmax** [comment]
Tests are part of the documentation because they are examples, and [there are tests around `ignore`](https://github.com/magmax/python-inquirer/blob/master/tests/unit/test_question.py#L20-L48).

Anyway, I'm documenting them in a better way
