### ISSUE TITLE
How do I actually pick an answer in a checkbox?

### ISSUE THREAD

**Issue by preeth1** [magmax/python-inquirer#98]
I am trying to run this example:
https://python-inquirer.readthedocs.io/en/latest/examples.html#checkbox-py

I scroll down to an answer and hit `Enter` on my keyboard to try to check off one item, but it immediately exits the prompt with only that one selection. How do I actually use this? I don't see it in the docs anywhere. Thanks!

**Comment by magmax** [comment]
Just one? It should return two of them.

You can select as many as you want with space.

--
Sorry for being so brief, but I'm writing you from my mobile.

**Comment by H0R5E** [comment]
It took me a while to work this out as well. It would be good if it was explicitly written in the documentation for checkbox, especially in the README. Happy to do a quick PR if that would help.

Mat
